### ISSUE TITLE
var myVariables is not a great name

### ISSUE THREAD

**Issue by Razpudding** [ChanelZM/webapp_from_scratch#7]
Try to think of something more descriptive. Only group vars in an object when that object makes sense. If you cant give a name to it because it combines random things, it might be better to let those random things be random things of their own.
If you want the variables to be static references to something, like a reference to an HTML element, maybe ES6' `const` might be what you;re looking for.

**Comment by ChanelZM** [comment]
Fixed a while back. Forgot to close this one.
